In [62]:
import pandas as pd
import matplotlib.pyplot as py

In [63]:
df = pd.read_csv("C:/Users/Dhruv/Downloads/used_cars_data.csv")
df.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

In [64]:
df.duplicated().sum()

np.int64(0)

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   str
 2   Location           7253 non-null   str
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   str
 6   Transmission       7253 non-null   str
 7   Owner_Type         7253 non-null   str
 8   Mileage            7251 non-null   str
 9   Engine             7207 non-null   str
 10  Power              7207 non-null   str
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   str
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), str(9)
memory usage: 793.4 KB

In [66]:
df.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50

Dropping the unwanted Columns and Row's Values

In [67]:
df.drop(columns=['S.No.','New_Price'],inplace=True)
df.dropna(subset=['Price'],inplace=True)
df.head(3)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,4.50

Splitting the unwanted parts from Mileage,Engine and Power and converting it to float dtype

In [68]:
df['Mileage'] = pd.to_numeric(df['Mileage'].str.split().str[0], errors='coerce')
df['Engine'] = pd.to_numeric(df['Engine'].str.split().str[0], errors='coerce')
df['Power'] = pd.to_numeric(df['Power'].str.split().str[0], errors='coerce')

df.head(3)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,4.50

In [69]:
df.isnull().sum()

Name                   0
Location               0
Year                   0
Kilometers_Driven      0
Fuel_Type              0
Transmission           0
Owner_Type             0
Mileage                2
Engine                36
Power                143
Seats                 42
Price                  0
dtype: int64

In [70]:
df['Mileage'] = df['Mileage'].fillna(df['Mileage'].median())

In [74]:
df['Engine'] = df['Engine'].fillna(df.groupby('Name')['Engine'].transform('median'))
df['Power']  = df['Power'].fillna(df.groupby('Name')['Power'].transform('median'))
df['Engine'] = df['Engine'].fillna(df['Engine'].median())
df['Power']  = df['Power'].fillna(df['Power'].median())

In [77]:
df['Seats'] = df['Seats'].fillna(df['Seats'].mode()[0])

In [78]:
df.isnull().sum()

Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

In [81]:
df['Name'].value_counts()

Name
Mahindra XUV500 W8 2WD                        49
Maruti Swift VDI                              45
Honda City 1.5 S MT                           34
Maruti Swift Dzire VDI                        34
Maruti Swift VDI BSIV                         31
                                              ..
Hyundai Elantra SX                             1
Maruti Wagon R Duo Lxi                         1
Volkswagen Polo IPL II 1.2 Petrol Highline     1
Tata Bolt Revotron XT                          1
Mahindra Xylo D4 BSIV                          1
Name: count, Length: 1876, dtype: int64

In [87]:
df.to_csv('used_cars_cleaned.csv', index=False)

In [88]:
df.to_csv(r"C:\Users\Dhruv\Downloads\used_cars_clean.csv", index=False)